<Project>

	<Import Project="Versions.Details.props" />

	<PropertyGroup>
		<VersionPrefix>1.0.0</VersionPrefix>
		<PreReleaseVersionLabel>beta</PreReleaseVersionLabel>

		<!-- Arcade features -->
		<UsingToolXliff>false</UsingToolXliff>
	</PropertyGroup>

	<PropertyGroup>

		<ExampleVersion>16.0.527</ExampleVersion>
	</PropertyGroup>

</Project>
